version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=<your-api-base-url>
      - VITE_APPLICATION_NAME=<your-application-name>
      - VITE_TIMEOUT=<your-timeout>
    volumes:
      - ./src:/app/src  # For development hot-reload
    restart: unless-stopped 